### ISSUE TITLE
Sign up Sizing

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/saas-website#2]
Hi! My form doesn't completely show in the small and xs small sizes, and when it gets bigger its not in the center like it should be @muxlowc 
<img width="496" alt="Screen Shot 2020-04-15 at 10 42 05 AM" src="https://user-images.githubusercontent.com/55193092/79350707-caab2800-7f05-11ea-99ed-7f591d9bdb07.png">
<img width="1310" alt="Screen Shot 2020-04-15 at 10 42 12 AM" src="https://user-images.githubusercontent.com/55193092/79350710-cb43be80-7f05-11ea-8cc2-5223864b353c.png">

**Comment by muxlowc** [comment]
@heatherlyall okay i think i got it!

I just changed around a couple things:

Main.css:
.banner-content {
  top: 0;
  left: 0;
  right: 0;
  position: absolute;
  color: #fff;
  text-align: center;
}

.banner-img {
  height: 100vh;
  width: 100%;
}

.banner {
  position: relative;
  overflow: hidden;
}

sign-up.html
( i took out the img-flex from your banner image, and added a banner-img class)
```
<div class="banner">
      <img class="banner-img" src="images/lightsticks.jpg" alt="">
      <div class="banner-content text-center">
```

**Comment by heatherlyall** [comment]
Thank you!! @muxlowc :)
